### ISSUE TITLE
Photo support

### ISSUE THREAD

**Issue by Zaprit** [Zaprit/HugeSpaceship#9]
Similar to levels, photos will need to be supported. For photos to work we will need:
- [ ] the /uploadPhoto endpoint
- [ ] the /photos endpoint
- [ ] db support for the two

**Comment by explosiveSlug2004** [comment]
dont worry buddy i got you
![goku](https://github.com/Zaprit/HugeSpaceship/assets/121770564/2ac83b3c-cbcc-452c-919f-875d48b42ed8)

**Comment by Zaprit** [comment]
ok
